[package]
name = "hyperlight-wasm-aot"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = { version = "33.0.0", default-features = false, features = ["cranelift", "runtime", "component-model" ] }
clap = "4.5"
cargo_metadata = "0.19"
